matrix:
  include:
    - language: java
      jdk:
        - oraclejdk9
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.gradle"
    - "~/.gradle"
before_install:
  - chmod a+x gradlew
script:
  - "./gradlew clean test"