version: "3"
services:
  test:
    image: openjdk:8
    working_dir: /root/app
    volumes:
      - ./:/root/app
      - ~/.gradle/:/root/.gradle
    command: ./ops/test.sh

  build:
    image: openjdk:8
    working_dir: /root/app
    volumes:
      - ./:/root/app
      - ~/.gradle/:/root/.gradle
    command: ./gradlew clean jar

  release:
    build:
      context: .
    image: banking-classification